Java spring boot
navikt/veilarbfilter pull request #113
Opened 2022-03-09 12:31 UTC by dragutin-nav

2022-03-10 12:35 UTC, matiasvinjevoll requested changes

2022-03-10 13:57 UTC, dragutin-nav commented on .github/workflows/main.yml
> +          MAVEN_OPTS: -Xss1024M -Xmx2048M
nope, skal fikse..

2022-03-10 13:59 UTC, dragutin-nav commented on .github/workflows/main.yml
> +        run: mvn -s settings.xml -P github -Dgithub.token=${{ secrets.GITHUB_TOKEN }} -B package -D skipTests
done

2022-03-10 14:01 UTC, dragutin-nav commented on src/main/java/no/nav/pto/veilarbfilter/repository/VeilederGruppeFilterRepository.java
> +        //TODO("Not yet implemented");
a, we dont support sorting for veileder gruppe...it was @todo before as well..eventually we will do that, but I doubt

2022-03-10 14:02 UTC, dragutin-nav commented on src/main/java/no/nav/pto/veilarbfilter/rest/MineLagredeFilter.java
> +public class MineLagredeFilter {
Done

2022-03-10 14:02 UTC, dragutin-nav commented on src/main/resources/application.properties
> +spring.main.allow-bean-definition-overriding=true
Yep, in order to run tests, since for tests we are overwriting DataSource bean

2022-03-10 15:11 UTC, matiasvinjevoll commented on src/main/resources/application.properties
> +spring.main.allow-bean-definition-overriding=true
Men burde den ikke da være i `application-test.properties`? Så unngår man test-konfigurasjon i prod.

2022-03-10 15:48 UTC, dragutin-nav commented on src/main/resources/application.properties
> +spring.main.allow-bean-definition-overriding=true
Yep, true. I will fix

2022-03-11 11:21 UTC, stianStensli commented on src/main/java/no/nav/pto/veilarbfilter/config/ScheduleConfig.java
> +            metricsReporter.reportLagradeFilter();
Hvis vi klarer å bruke Prometheus så er vel denne appen også kjempe enkel å få over til GCP? 🚀

2022-03-11 11:24 UTC, stianStensli commented on src/main/java/no/nav/pto/veilarbfilter/config/ScheduleConfig.java
> +    @Scheduled(cron = "30 * * * * ?")
Kanskje nice å endre denne til å bruke @Scheduled(fixedDelay = 30_000)

Da er det veldig tydelig at den kjører med 30s mellomrom

2022-03-11 11:54 UTC, dragutin-nav commented on src/main/java/no/nav/pto/veilarbfilter/VeilarbfilterApp.java
> +        TimeZone.setDefault(TimeZone.getTimeZone(Optional.ofNullable(System.getenv("TZ")).orElse("Europe/Oslo")));
yep yep, I will remove that

2022-03-11 11:56 UTC, dragutin-nav commented on src/main/java/no/nav/pto/veilarbfilter/client/VeilarbveilederClient.java
> +                .expireAfterWrite(10, TimeUnit.HOURS)
Agree, good catch!

2022-03-11 11:57 UTC, dragutin-nav commented on src/main/java/no/nav/pto/veilarbfilter/config/ApplicationConfig.java
> +    public AbacClient abacClient(EnvironmentProperties properties, Credentials serviceUserCredentials) {
Done

2022-03-11 11:57 UTC, dragutin-nav commented on src/main/java/no/nav/pto/veilarbfilter/config/ApplicationConfig.java
> +    public Pep veilarbPep(Credentials serviceUserCredentials, AbacClient abacClient) {
Thanks! Fixed

2022-03-11 11:59 UTC, dragutin-nav commented on src/main/java/no/nav/pto/veilarbfilter/config/ApplicationConfig.java
> +    public ObjectMapper objectMapper() {
Nope, I need to have some control over date serialization/deserialization. Thats there are additional modules in ObjectMapper

2022-03-11 12:08 UTC, matiasvinjevoll approved these changes

2022-03-11 12:56 UTC, dragutin-nav commented on src/main/java/no/nav/pto/veilarbfilter/config/DbConfigPostgres.java
> +                .baselineOnMigrate(true)
Hm, I am not sure, I can remove that.

2022-03-11 12:56 UTC, dragutin-nav commented on src/main/java/no/nav/pto/veilarbfilter/config/ScheduleConfig.java
> +            metricsReporter.reportLagradeFilter();
It will be done in next version :)

2022-03-11 12:58 UTC, dragutin-nav commented on src/main/java/no/nav/pto/veilarbfilter/repository/MineLagredeFilterRepository.java
> +            validerFilterNavn(filter.getFilterNavn());
That is maybe metter of preference. We don't have strict rules when validation should occur.

2022-03-11 12:58 UTC, dragutin-nav commented on src/main/java/no/nav/pto/veilarbfilter/repository/MineLagredeFilterRepository.java
> +            ObjectMapper objectMapper = new ObjectMapper();
Nope, that one is unecessary. Thank you for noticing this!

2022-03-11 12:59 UTC, dragutin-nav commented on src/main/java/no/nav/pto/veilarbfilter/repository/VeilederGruppeFilterRepository.java
> +    private void validerUnikhet(Boolean navn, Boolean valg) {
fjernet

2022-03-11 13:09 UTC, merged