Migration to azure ad
navikt/veilarbfilter pull request #72
Opened 2020-11-23 21:56 UTC by dragutin-nav

2020-11-25 19:19 UTC, dragutin-nav commented
@AlexGaard , @pederpus kan du sjekke, er du snill.

2020-11-26 08:14 UTC, AlexGaard requested changes

2020-11-26 08:14 UTC, AlexGaard commented on src/main/no/nav/pto/veilarbfilter/routes/MineLagredeFilterRoutes.kt
> +        return this.principal<JWTPrincipal>()?.payload?.getClaim("NAVident")?.asString();
Ville kanskje hentet `this.principal<JWTPrincipal>()?.payload?.getClaim("NAVident")` ut som en variabel og gjort en sjekk på at den ikke er null, så slipper man å hente den ut flere ganger.

2020-11-26 08:14 UTC, AlexGaard commented on src/main/no/nav/pto/veilarbfilter/JwtUtil.kt
> +        fun useAzureJwtFromCookie(call: ApplicationCall): HttpAuthHeader? {
Siden useJwtFromCookie og useAzureJwtFromCookie er nesten identiske, så ville jeg heller laget 1 funksjon som er litt mer generisk. F.eks fun` useJwtFromCookie(call: ApplicationCall, cookieName: String)`

2020-11-26 08:14 UTC, AlexGaard commented on src/main/no/nav/pto/veilarbfilter/HttpHandler.kt
> +            skipWhen { applicationCall -> applicationCall.request.cookies["isso-idtoken"] == null }
Siden vi kommer til å bruke "isso-idtoken" og "ID_token" flere ganger i koden, så tenker jeg det kunne vært greit å lage en konstant for hver av de

2020-11-26 08:15 UTC, AlexGaard commented
Tror det hadde vært fint å squashe alle commitsene til 1, så blir det litt penere historikk :)

2020-11-26 10:15 UTC, dragutin-nav commented
Takk @AlexGaard , jeg skal fikse dette problemer..

2020-11-26 21:12 UTC, dragutin-nav commented
@AlexGaard kanskje du kan sjekke koden igjen etter endringer...commits squashed.

2020-12-03 10:36 UTC, merged